### ISSUE TITLE
GitHub dark mode doesn't look very good

### ISSUE THREAD

**Issue by ajkblue** [Gofake1/Nightlight#1]
When dark mode is enabled on GitHub the website doesn't look very good and some text is difficult to read. Do you plan on adding any custom stylesheets for certain websites or do they all use the same general ruleset? But as an aside, I've been looking for an app like this for a long time, and am excited to see how this matures!

**Comment by Gofake1** [comment]
I personally use [Stylish](https://github.com/350d/stylish) for Github instead of Nightlight. There is also an unavoidable inefficiency due to Nightlight having to walk the entire DOM tree, which you can notice on any webpage with a lot of elements (such as a long Github source code page), so that's another point in favor of Stylish.

That being said, can you can post a screenshot of the offending page(s)? I realize that you might not want to use another extension as a workaround.

**Comment by ajkblue** [comment]
Yeah, I'm kinda hoping not having to install more extensions than I already have. But here are a few examples, being a projects' homepage (description and buttons are difficult to read) as well as issue pages have funny white lines everywhere.
![darkmode](https://cloud.githubusercontent.com/assets/9651939/26517489/e1e7af50-4256-11e7-8044-8fc9d03b3c82.png)
![darkmode2](https://cloud.githubusercontent.com/assets/9651939/26517491/e59b33ce-4256-11e7-8848-48effc002733.png)

**Comment by ajkblue** [comment]
Also, I don't know if this needs to be opened as a separate issue, but the automatic night mode feature doesn't seem to be working right

**Comment by Gofake1** [comment]
Did you recently update Nightlight? You'll need to refresh the page after updating.
If that isn't the case, wait for a day and see if it still doesn't work.

**Comment by ajkblue** [comment]
Yes I have, I just barely got version 0.1.2 late yesterday I believe. I'll do further testing to verify this issue though, and get back with you.

**Comment by ajkblue** [comment]
After using this for a few days, it doesn't seem like the automatic feature to turn nightlight on and off isn't working. I have it set to turn on at 22:00 and off at 8:00, yet it never does. I still have to manually click on the button in the menu bar to turn it off and on everyday. Is there something I'm missing or something that's not working right here?

**Comment by Gofake1** [comment]
Just to make sure, did you tick the "Automatic" checkbox? Did you also restart Safari? That usually fixes the problem for me. Otherwise I don't know how to reproduce the issue.

**Comment by ajkblue** [comment]
After doing a restart and cleaning the cache, the automatic switching seems to be working now. This issue can be closed unless there's something you're able to do to make GitHub a little more legible

**Comment by Gofake1** [comment]
I'm working on something called Aggressive Mode that should improve Github's appearance.

**Comment by Gofake1** [comment]
v0.1.4 was accepted by Apple today; it contains Aggressive Mode, which fixes the appearance of the Github buttons.

**Comment by ajkblue** [comment]
It looks good to me! Thank you so much for making this, I've been looking for something like this for Safari for years
