### ISSUE TITLE
Thoughts on Safari App Extension

### ISSUE THREAD

**Issue by Gofake1** [Gofake1/Nightlight#10]
In case you haven't heard, Safari 12 will deprecate Javascript extensions, and Apple will stop accepting updates to the Gallery after 2018.

A native Safari App Extension offers some advantages:
* System support for querying the user's location
* Foundation provides a Timer class (my current implementation of timers in global.html is low-effort)

Since this is the only way forward, I will stop maintaining the Javascript extensions.

In other news, I will change how Nightlight works (from walking the DOM to injecting stylesheets). This should be both more efficient and produce better-looking results.

I haven't been updating Nightlight for a while, and this is my way of letting everyone know that it will continue to be a while before Nightlight reaches 1.0. Thanks for your patience.

**Comment by MentalGear** [comment]
Cool, thanks for the update. Wouldn't it be great if the new nightlight would be ready for Mojave ? :)
I'm curious: What changes do you plan to make nightlight perform more efficently ?

**Comment by Gofake1** [comment]
Web browsers already implement a way to efficiently update the appearance of multiple elements by way of CSS. The current Nightlight design uses MutationObserver and the DOM API to update the appearances of elements. This works, but there are edge cases where this is suboptimal (see my [blog post](https://gofake1.net/blog/nightlight_mutation_observer.html)).

The new design I have in mind takes a webpage's stylesheets, "darkens" them, and injects them back and overrides the originals. The "darkening" process could be expensive, so the generated stylesheets will probably be cached.

**Comment by Gofake1** [comment]
The app extension is at a point where I'm happy with it. It's not a perfect translation from the old JS extension because the native SafariServices API is more limited:
* doesn't provide notifications for when user changes tab/window

Native code provides some advantages:
* using Foundation.Timer results in more robust auto-on/off

Modifying CSS works better than modifying DOM elements directly in most cases:
* haven't run into any cases where I've wanted a whitelist/blacklist
* there is the Safari bug that prevents this from working in a lot of cases, so we currently apply a translucent black style to everything

I'm going to start preparing for a release on the App Store.

**Comment by MentalGear** [comment]
Thanks for the update, David. If you still need a beta tester let me know ! :)
