### ISSUE TITLE
Is it possible to make Nightlight compatible with sVim link hints

### ISSUE THREAD

**Issue by nikitavoloboev** [Gofake1/Nightlight#14]
I opened an issue about it in sVim repo here:

https://github.com/flipxfx/sVim/issues/101 

But I think it's something only Nightlight can fix. 

With Nightlight on:

![dark](https://user-images.githubusercontent.com/6391776/46002437-55bb9780-c0ae-11e8-8d06-b40fe27634df.png)

WIth Nightlight off:

![2018-09-25 at 10 32](https://user-images.githubusercontent.com/6391776/46002454-610ec300-c0ae-11e8-94c0-896d15aa3fac.png)

As you can see, the letters in the colored boxes are clearly seen in the off version.

I would love to have both extensions work well together. I really rely on sVim for my work and I am loving using Nightlight now that Mojawe has been released.

Thank you.

**Comment by Gofake1** [comment]
I would recommend you set a custom style for `.sVim-hint` in sVim's settings, marking the `background-color` and `color` with `!important`.
You could also customize Nightlight by putting custom CSS for `.sVim-hint` in the injected script (`GENERAL-HACKS` seems like the logical place to put it).
I am against the idea of tailoring to a specific user's environment; that should be left to your own fork.
