### ISSUE TITLE
Add a way to add a website quickly to a blacklist

### ISSUE THREAD

**Issue by nikitavoloboev** [Gofake1/Nightlight#3]
Perhaps from a hotkey or from the menu bar option.

Currently I can ignore tab but that is not very useful since on some sites Nightlight is broken. I would like to blacklist those sites quickly.

Thank you.

**Comment by nikitavoloboev** [comment]
Also for some reason, option + N, O are not working at all for me. :(

**Comment by Gofake1** [comment]
Do you find yourself adding to the blacklist often, or is it more of a one-time pain point?

**Comment by nikitavoloboev** [comment]
Actually you are right, it's not that common to add a website to blacklist, it's easier to just turn off nightlight for that website temporarily and have a blacklist only for most common sites. :)
