### ISSUE TITLE
Possible to use it as a boomarklet in iOS Safari?

### ISSUE THREAD

**Issue by melangue** [Gofake1/Nightlight#4]
First of all thank you for this extension, it works quite reliably.  
Would it be possible to modify the js in some way to make it work as a mobile Safari bookmarklet?  
I'm nowhere capable enough to pull it of by myself.

**Comment by Gofake1** [comment]
Here's a preliminary version:
[https://gofake1.net/projects/nightlight.html#bookmarklet]()

**Comment by melangue** [comment]
Thank you, it works perfectly! :)
