### ISSUE TITLE
Nightlight stopped respecting filters I set

### ISSUE THREAD

**Issue by nikitavoloboev** [Gofake1/Nightlight#5]
I set various websites as blacklist in settings and yet Nightlight is still working on them. Not sure what to do. :( 

It was working well before.

**Comment by nikitavoloboev** [comment]
I think the issue was that I had a space somewhere in the blacklist. It is fixed after that.

**Comment by Gofake1** [comment]
For now, Nightlight doesn't handle whitespace in the blacklists.

**Comment by Gofake1** [comment]
I noticed I actually introduced a bug a few commits ago that broke filter lists. I fixed it in the latest commit.

**Comment by nikitavoloboev** [comment]
Where can I get an updated version? 

Right now Nightlight blacks out all websites not taking into account what I put in the blacklist. :(

**Comment by Gofake1** [comment]
I've submitted an update to Apple, but for now you can download v0.1.5 at the [releases](https://github.com/Gofake1/Nightlight/releases) page.

**Comment by Gofake1** [comment]
Apple finally updated the Gallery version to v0.1.5.
