### ISSUE TITLE
Add one more hotkey mapping please

### ISSUE THREAD

**Issue by nikitavoloboev** [Gofake1/Nightlight#6]
Sorry to ask you this again. But is it possible to add one more mapping (cmd + shift + f).

The reason is that I can't use opt key and my control key is too valuable for me as it is filled with other very valuable things to me. 

A mapping to cmd + shift + f or some cmd + shift variation would be really big for me. 

I tried adding it myself looking at [this commit](https://github.com/Gofake1/Nightlight/commit/6dd5ffe82052061abff0ba9a649f8491a89884a6) however I am bit confused by the code of it, was quite hard to make sense of it.

I would greatly appreciate if you were to add it. I don't think it hurts the performance of the extension too, I think it shouldn't.

**Comment by Gofake1** [comment]
I added '⇧⌘F' as an option. This will be included in v0.1.6 when that's eventually finished.

**Comment by Gofake1** [comment]
Version 0.1.6 has been accepted to the Extension Gallery.
