### ISSUE TITLE
Automatically turn on at XX time is not working?

### ISSUE THREAD

**Issue by leeummm** [Gofake1/Nightlight#7]
I have it set to turn on at 23:30 and off at 8:00. Am i typing it in wrong?

**Comment by leeummm** [comment]
I have been messing around and it seems that you need to enter time in military time. However, if I set the time to go past the 24hr mark, for example

Turn on at: 23:00

Turn off at: 8:00

It breaks it and it won't activate automatically.

**Comment by Gofake1** [comment]
Military time is the expected format. You should be able to do what you described; could you give it a day and see if it works?

**Comment by leeummm** [comment]
Hey there,

Sadly the issue is still here. It is 11 where I live, I have the time to turn on set to 23:00, and it still doesn't work. Unsure what exactly is causing the issue.

**Comment by leeummm** [comment]
Interesting, woke up today and nightlight had activated itself at 8 AM. I think this confirms my theory. The code seems to assume that turn on time must be less than turn off time (therefore you cant set it for overnight schedules).

**Comment by Gofake1** [comment]
Can you provide the version information for Safari and macOS?

**Comment by leeummm** [comment]
Safari 10.1.2
Mac OS 10.12.6

Nightlight 0.1.5

Also running: Wipr, Omnikey, RES

**Comment by Gofake1** [comment]
I set my options to turn on at 21:00 and turn off at 8:00. Could you try setting the on time to something earlier than 23:00?

**Comment by leeummm** [comment]
Alright set it for 21:00 as well. Do I need to check the "turn nightlight on automatically" box or not? Ive experimented with it off and on and the problem remains. What do you recommend

**Comment by Gofake1** [comment]
That option should be checked.

**Comment by leeummm** [comment]
Great. Will report back in the morning!

**Comment by leeummm** [comment]
Hey there, it is officially after 9 oclock here and nightlight has failed to activate. Totally unsure why.

**Comment by leeummm** [comment]
I decided to do a quick uninstall and then reinstall the app. It seems to be working now, however I did not check "automatically turn on nightlight". The only other thing that is different is I don't have websites blacklisted. I originally had the website URLs separated by commas, no idea if that was affecting it, or maybe my install was just bad.

**Comment by leeummm** [comment]
Aaaaand it failed to turn itself off this morning...

**Comment by Gofake1** [comment]
Was the automatic option checked?

**Comment by leeummm** [comment]
The automatic option was checked when it failed to turn itself off in the morning. It turned itself on automatically when the option was left unchecked.

**Comment by Gofake1** [comment]
Could you try enabling the developer menu and emptying caches?
Go to Preferences > Advanced, check "Show Develop menu in menu bar"
Click "Empty Caches" in the Develop menu.

**Comment by ajkblue** [comment]
I’ve has this problem as well, although for me emptying caches seemed to fix it temporarily but after a few days it quit working again.

**Comment by leeummm** [comment]
@Gofake1 great news, due to other problems on my mac, I had to reset SMC. Guess what works now? The automatic turn on feature. No clue why or how the SMC fixed it, but it seems to have fixed everything! Just in case someone else runs into this problem, thought i'd report

**Comment by Gofake1** [comment]
Reopen this issue if you run into problems again.
