### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by gitguys** [Gofake1/Nightlight#8]
I've looked around the website and now here at GH, but couldn't find it anywhere.  What's the privacy policy of this extension.  Does it collect any data and/or share it?  And, if so, what data is collected and how is it used?

**Comment by Gofake1** [comment]
I hope this is to your satisfaction: [https://gofake1.net/projects/nightlight.html#privacypolicy](https://gofake1.net/projects/nightlight.html#privacypolicy)
